- .env
- README.md
- nginx.dockerfile
> docker/new: allow custom SSL certificates. see readme.

- files/nginx/odk-setup.sh
- files/nginx/odk.conf.template
- files/service/scripts/start-odk.sh
1. Enable gzip on nginx.
2. Always rebuild the nginx conf file so it picks up conf changes.
3. Start using multithreaded node.
> Nginx and node improvements

- docker-compose.yml
- files/dkim/config.disabled
* the documentation contains information on enabling these.
> new: add inactive DKIM configuration artifacts.

- files/nginx/run_certbot.sh
- nginx.dockerfile
> bug: sending SIGHUP too quickly fails nginx out.

- LICENSE
- README.md
> repo #62: improve readme; add license file.

- nginx.dockerfile
- service.dockerfile
This reverts commits 6b96c0b, ac7fa72, and 40bbd24.
> Revert some of "operations updates for release v0.6"

- nginx.dockerfile
- service.dockerfile
still needs the subprojects to be updated. @matthew-white can you do that once the frontend state is correct?
> release v0.6

- .circleci/config.yml
- docker-compose.yml
> add a ci smoke test build

- .circleci/config.yml
* was never sure it actually worked and it costs money.
> test: no longer try to use docker layer caching for tests.

- docker-compose.yml
https://hub.docker.com/layers/getodk/pyxform-http/v1.3.4/images/sha256-00032256e5c165f7744fe5bfcc7092b23ab297753aa160f8c4e5d4831e01a86d?context=explore
> Upgrade pyxform to v1.3.4

- .github/ISSUE_TEMPLATE/config.yml
I think only having a contact link to the forum captures the workflow we want. I've made an attempt at clarifying how it should be used.
> Provide specific instructions for using the forum

- enketo.dockerfile
Currently running on the QA server. Should be merged after QA cycle.
> Upgrade to Enketo v3.0.0

- docker-compose.yml
Currently running on the QA server. Should be merged after QA cycle.
> Upgrade to pyxform v1.6.0

- enketo.dockerfile
> Upgrade to Enketo v3.0.1

- files/service/crontab
- files/service/scripts/purge-forms.sh
Cron job for a daily script that purges forms deleted over 30 days prior. The task and script are captured in this backend PR: getodk/central-backend#445
> Daily cron job for purging deleted froms

- docker-compose.yml
Should be added to https://github.com/getodk/central/pull/264
> Upgrade to pyxform v1.8.0

- enketo.dockerfile
I have tried this version on the QA server and verified basic submission and edit workflows. We've had a pre-release version with most of this code running on the QA server for about a month.
A new feature for the release notes is support for geoJSON external secondary instances (https://docs.getodk.org/form-datasets/#building-selects-from-geojson-files)
> Update Enketo to v4.1.0

- nginx.dockerfile
- secrets.dockerfile
- service.dockerfile
Helps with #282
Confirmed working on a new install. Encrypted project with submissions from Collect and download works.
> Upgrade to recent LTS OS

- files/nginx/common-headers.nginx.conf
- files/nginx/odk.conf.template
- nginx.dockerfile
Closes #303 
Similar changes for frontend dev @ https://github.com/getodk/central-frontend/pull/630
> nginx: set security headers at root path

- files/service/config.json.template
> Add support for Sentry organization subdomain

- nginx.dockerfile
- secrets.dockerfile
- service.dockerfile
new: updated node version to 16.17.0
> new: updated node version to 16.17.0

- files/enketo/config.json.template
PR should be merged for release with v2022.3
> Match Collect relevance behavior

- files/service/scripts/start-odk.sh
- service.dockerfile
Closes https://github.com/getodk/central-backend/issues/547?
Related: #316
> Pass version information to environment variables for Sentry

- files/service/pm2.config.js
- files/service/scripts/start-odk.sh
- service.dockerfile
Closes #
Tested locally
We can wait for pm2 team to fix the issue at their end. Ref: https://github.com/Unitech/pm2/issues/5450
NA
NA
> fix: start correct number of node instances

- service.dockerfile
> npm: use --omit=dev instead of --production

- service.dockerfile
Follow on from #358 ~~(please wait for that to be resolved before considering this)~~.
> service: npm ci: suppress noise

- enketo.dockerfile
5.0.2 has been running on our various test servers for some time.
Considered not upgrading it but there are some nice fixes in the latest version.
Definitely some but the release has been out for a month so limited.
No.
> Upgrade Enketo to 5.0.2

- docker-compose.yml
- enketo.dockerfile
- files/prebuild/build-frontend.sh
- files/service/crontab
- files/service/scripts/run-backup.sh
- service.dockerfile
This PR prepares the release of v2023.1. It only contains changes from other PRs that have already been approved and merged.
> Release v2023.1

- docs/news.html
@ktuite will merge this PR after merging #372. (Hence this PR branches off and targets the `master` branch, not `next`.) If we don't release on Friday, then @ktuite will update the date of the news item.
> Update news for v2023.1

- .circleci/config.yml
- files/service/odk-cmd
- files/service/scripts/start-odk.sh
Run shellcheck on CI to catch script issues early.
> ci: add shellcheck

- .github/PULL_REQUEST_TEMPLATE.md
Making a similar change as in getodk/central-frontend#738.
> Update text in PR template about code/assets from external sources

- enketo.dockerfile
Closes #384 -- no pyxform update this time
> Update Enketo to 6.0.0

- .circleci/config.yml
- files/service/scripts/start-odk.sh
- Exported `WORKER_COUNT` environment variable so that pm2 configuration file can access it
- Also added verification command in circle CI step
> Really fix pm2 & add verification step in circleci

- .circleci/config.yml
Tiny CI change for consistency.
> Update pm2 check to use docker compose

- enketo.dockerfile
- files/enketo/start-enketo.sh
- files/nginx/setup-odk.sh
- files/service/scripts/start-odk.sh
- service.dockerfile
This PR prepares the release of v2023.2.1. It should only contain changes from other PRs that have already been approved and merged (and possibly merge commits from the `master` branch).
> Release v2023.2.1

- enketo.dockerfile
- files/nginx/odk.conf.template
This PR prepares the release of v2023.3.1. It should only contain changes from other PRs that have already been approved and merged (and possibly merge commits from the `master` branch).
> Release v2023.3.1

- nginx.dockerfile
- secrets.dockerfile
- service.dockerfile
As per https://github.com/getodk/central-backend/pull/919#issuecomment-1621949441. Progress toward #432.
> Update to node v18

- enketo.dockerfile
- files/enketo/start-enketo.sh
Progress on #499 
Copied changes from dev server.
The one major decision point is around how to launch Enketo. We used to use `pm2-runtime`. Enketo has its own worker system to make use of multiple CPUs and Docker itself should provide restart in some failure cases. With this PR, I'm proposing launching node directly.
I think the biggest risk is around the process management strategy. I don't think `pm2-runtime` as it was used added anything but there may be some cases where it was helping with recovery or load balancing that I'm not thinking of.
There's also always risk around new Enketo versions. This is mostly a patch release with a major version bump because the Docker setup and the minimum node version have changed.
No.
> Update Enketo to 7.0.0

- .github/PULL_REQUEST_TEMPLATE.md
I'm sorry, I've been getting branch targeting wrong. I think a checklist item will be more effective as a reminder.
This is targeting `master` because it's an infrastructure change. 😊
Consulted my own psychology.
It requires an action so is more likely to be read. Did not consider any alternative.
Not user facing.
No.
> Add checklist item for branch targeting

- docker-compose.yml
- enketo.dockerfile
- files/enketo/start-enketo.sh
- files/postgres14/start-postgres.sh
- nginx.dockerfile
- postgres14.dockerfile
- secrets.dockerfile
- service.dockerfile
This PR prepares the release of v2023.5. It should only contain changes from other PRs that have already been approved and merged (and possibly merge commits from the `master` branch).
> Release v2023.5

- docs/news.html
> Update news for v2023.5

- nginx.dockerfile
Point release is out so we should use that
> Upgrade to non-tagged release of nginx

- files/nginx/odk.conf.template
See:
* http://www.robotstxt.org/robotstxt.html
* https://serverfault.com/questions/549332/how-to-set-robots-txt-globally-in-nginx-for-all-virtual-hosts#751841
> Add robots.txt

- docker-compose.yml
- enketo.dockerfile
- nginx.dockerfile
- secrets.dockerfile
> V2024.1 updates

- service.dockerfile
#637 updated Node for `nginx` and `secrets`, but I think we need to do so for `service` as well.
> Update Node version for service

- docs/news.html
> Update news for v2024.1

- docs/news.html
This PR adds an announcement to news about the release of v2024.2.
> Update news for v2024.2

- docs/news.html
This PR updates the news following the release of v2024.2.1.
> Update news for v2024.2.1

- docs/news.html
This PR updates news.html for the release of v2024.3.
> Update news for v2024.3

- docs/news.html
> News for 2024.3.1 patch release

- test/test-images.sh
Closes #892
CI
Could increase longer?  There's always a chance we don't wait long enough in some circumstances
No affect for users.
No.
> test-images: wait longer for frontend/nginx to start

- enketo.dockerfile
This PR prepares the release of v2024.3.2. It should only contain changes from other PRs that have already been approved and merged.
> Release v2024.3.2

- files/nginx/odk.conf.template
- test/nginx/test-nginx.js
Corresponding change of https://github.com/getodk/central-frontend/pull/1198
> Fix: dont match thanks page for enketo redirection

- test/nginx/files/nginx-test/acme-challenge
- test/nginx/files/nginx-test/http_root/index.html
- test/nginx/files/nginx-test/http_root/should-be-cached.txt
- test/nginx/files/nginx-test/http_root/version.txt
These files are no longer used, and their presence is misleading.
These are nominally test files.  The tests still pass without them.
Yes.
It does not.
It does not.
> test/nginx: remove unused files

- files/nginx/odk.conf.template
- test/nginx/test-nginx.js
Noted while working on https://github.com/getodk/central/pull/986
It can be hard to reason about exactly where a rewrite rule will end up being processed.  These test additions ensure that the correct CSP is applied to various paths.
Ran the updated tests.
This should make the current definition of CSPs easier to read, and make future changes easier to track.
Previously discussed at https://github.com/getodk/central/pull/936#discussion_r2015734746
No effect.
> test/nginx: add explicit checks for CSP contents

- files/nginx/odk.conf.template
- files/prebuild/build-frontend.sh
- test/nginx/test-nginx.js
> Updated central-frontend URLs for cache strategy to reflect vite output

- docs/news.html
> Update news for v2025.1

- .env.template
This PR prepares the release of v2025.1.1. It should only contain changes from other PRs that have already been approved and merged (and possibly merge commits from the `master` branch).
> Release v2025.1.1

- docs/news.html
This PR updates news.html to announce the new patch release v2025.1.1. This PR intentionally targets the `master` branch.
> Update news for v2025.1.1

- docs/news.html
This PR updates news.html to announce the release of v2025.1.2.
> Update news for v2025.1.2

- files/nginx/odk.conf.template
- test/nginx/test-nginx.js
Closes https://github.com/getodk/central/issues/1129
Added tests, checked tests pass.
Ongoing consideration of scrapping CSP or using a much more permissive base, but not directly relevant to this change.
It may reduce traffic to `/csp-report`.
No.
> csp: add exceptions for Google Translate

- .github/workflows/test.yml
- docker-compose.yml
- nginx.dockerfile
- secrets.dockerfile
- service.dockerfile
- test/nginx/package-lock.json
- test/nginx/package.json
> V2025.2 deps

- docs/news.html
> Update news for v2025.1.3

- docs/news.html
Updates news for latest release.
> Update news for v2025.1.4

- docs/news.html
This PR updates news.html to announce the release of v2025.2.1.
> Update news for v2025.2.1

- files/prebuild/build-frontend.sh
- test/nginx/test-nginx.js
* demonstrate the current support for compression algorithms
* provide framework for enabling more compression algorithms
Related:
* https://github.com/getodk/central/issues/1320
* https://github.com/getodk/central/issues/1319
New tests.
The not-enabled test is not necessarily very interesting, but I think helpful to know what currently works.
No effect.  Hopefully future related work will make their lives incrementally more streamlined.
No.
> nginx: add test for compression algorithm support

- docs/news.html
This PR updates news.html for the upcoming patch release.
> Update news for v2025.2.3
