files/nginx/odk.conf.template

* so large CSVs that are form attachments download compressed.
demonstration:
```
cxlt@durindana:forms$ http get https://odk.antinod.es/v1/forms/form/attachments/mydata.csv 'Authorization: Bearer <snip>' --verbose
GET /v1/forms/form/attachments/mydata.csv HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Bearer <snip>
Connection: keep-alive
Host: odk.antinod.es
User-Agent: HTTPie/1.0.0
HTTP/1.1 200 OK
Connection: keep-alive
Content-Disposition: attachment; filename="mydata.csv"
Content-Encoding: gzip
Content-Type: text/csv; charset=utf-8
Date: Tue, 18 Dec 2018 02:09:48 GMT
ETag: W/"22014-2irQT/ZnnPrSDAfrpKkm14fQBXI"
Server: nginx
Strict-Transport-Security: max-age=31536000
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Powered-By: …
```

improve: apply http compression to downloaded csv files.

---

files/nginx/default
files/nginx/odk.conf.template

* adding nginx extras made the variables hashtable bigger.
* text/html is automatically compressed.

improve: fix nginx warnings on boot.

---

docker-compose.yml
mail.dockerfile

* we only layered on it to install security updates. now those are baked
in upstream.

mail: use the base namshi/smtp image again now that it's up-to-date.

---

files/nginx/inflate_body.lua

* there is a filesize threshold above which nginx will still accept the
file, but it will spool it to disk rather than store it in memory.
* in this case, the lua interface changes and the file must be read.
* so we do that here.
* a lua expert should probably review this...

nginx: unzip uploads that were large enough to spool to disk.

---

docs/news.html

Analytics code is what Google provided. The UA key is owned by the Open Data Kit account and @issa-tseng has read access.

Measure usage as proxy for number of deployments

---

files/nginx/run_certbot.sh
nginx.dockerfile

this fixes #120, where the following error appears in the Docker logs when starting the nginx container:
> Error: urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555.
after updating staticfloat/nginx-certbot to fix that, a different error greets us:
```
nginx       | + parse_keyfiles /etc/nginx/conf.d/odk.conf.nokey
nginx       | + sed -n -e s&^\s*ssl_certificate_key\s*\(.*\);&\1&p /etc/nginx/conf.d/odk.conf.nokey
nginx       | /scripts/run_certbot.sh: 32: /scripts/run_certbot.sh: Bad substitution
```
using bash as the interpreter for `run_certbot.sh` makes this complaint go away. it looks like nginx-certbot is using bash for all its shell scripts …

bug #120: use newer nginx-certbot Docker image.

---

docker-compose.yml

As requested, @lognaturel. The commits since v0.3.0 are at https://github.com/yanokwa/pyxform-http/compare/v0.3.0...master. The key changes are 
1. Add support for external itemsets csv https://github.com/yanokwa/pyxform-http/pull/8
1. Upgrade to pyxform v1.x https://github.com/yanokwa/pyxform-http/commit/fdf50cde5dc4109869aa5e52db72ab39449c01ed
I propose that you approve and @issa-tseng merge.

Upgrade to pyxform v1.1.0

---

README.md

It's definitely possible to get to the dev setup instructions from the contributing guides for frontend and backend but it's disorienting not to have them front and center.

docs: add explicit link to development setup

---

files/enketo/config.json.template

We use support@getodk.org everywhere now and I think it's ultimately a better email address for this kind of issue.

Change to more generic email address

---

docker-compose.yml
enketo.dockerfile

I looked at the Enketo changelog and saw the upgrades mostly involve bug fixes. 2.5.3 came out earlier today but it looks very safe (and helpful) so I'd rather update right to it, especially since we'll have some time in QA.
pyxform-http has the same version of pyxform that has been out on XLSForm online.

Update Enketo to 2.5.3 and pyxform-http to 1.3.3

---

.github/ISSUE_TEMPLATE/config.yml

Sorry about the back and forth for something that should be simple, @matthew-white! This stuff feels different when it's actually deployed. I think we should move all the ODK repos in this direction so ideally we can get it right on this one first.
Goals here are to direct people more towards the right place and generally be a little friendlier.
CC @yanokwa

Separate out forum links from issue menu

---

docker-compose.yml

Key improvements
* Upgrade to pyxform v1.5.0
* Switch to gunicorn to reduce memory leaks and use older binaries for smaller size
* Upgrade deps, support for percent-coded form ids
I have not actually tested this PR inside Central, but risk should be pretty low. It'd be nice if this could be put though it's paces on a dev box long before the next release.

Update pyxform-http to 1.5.0

---

files/service/scripts/start-odk.sh

I'll use this branch to update the submodules for v1.2. I'm also committing a path change that follows from getodk/central-backend#331. @issa-tseng, I think this is the only change needed to `central` after the Backend refactor — is that right?

Update submodules for v1.2

---

.env
.env.template
docker-compose.yml
files/nginx/odk-setup.sh

This builds on the PR at https://github.com/getodk/central/pull/182 from @aiqui. Fixes #213.
It'd be nice to have this functionality for ODK Cloud so we can manage SSL at the load balancer rather than within nginx.
Changes
* I don't love hiding variables from people, so instead of `none`, which suggests to people that they don't need SSL, I call it `upstream`. Open to changing the name and open to hiding it.
* Updated output message to reflect the above
Additional, unrelated change:
* Moved variables to .env.template to make it easier to evolve without triggering merge conflicts. I believe this will not delete existing .env files that have changes, but I haven't verified this.

Add support for upstream SSL

---

.circleci/config.yml
docker-compose.yml

The use of [container_name](https://docs.docker.com/compose/compose-file/compose-file-v3/#container_name) means that you can't run multiple instances of Central on the same machine. 
It also means you can't ever have a container called mail or service or secrets. Removing the container name solves this problem because Docker automatically prepends the folder name to the container (e.g., service becomes central_service_1). This happens with our PostgreSQL container already since it doesn't have a container_name.
This isn't a must have change, so if it feels high risk, I'm open to waiting until after v1.2

ops: allow for multiple instances

---

README.md

In response to to https://github.com/getodk/central-frontend/pull/467#issuecomment-857769473, further addresses issue #219.
I took out the bit about testing enketo by checking out a specific fork in production because it's not necessary anymore and seems like a challenging way to do enketo-related development.
But one argument for keeping it is that maybe that nugget of information isn't well-captured somewhere else? Ehh.. what nugget am I talking about? The nugget of checking out a specific commit and following the [upgrade instructions](https://docs.getodk.org/central-upgrade/) while not running `docker-compose down`.

Changed main readme to mention Enketo in development

---

docker-compose.yml

Closes #231. For this PR, I verified that on the QA server...
* `docker-compose logs service` outputs logs
* `sudo docker ps -qa | sudo xargs docker inspect --format='{{.LogPath}}' | sudo xargs ls -hl` shows a reduction in log size
* `docker inspect <container>` shows max-file as a config
As detailed at https://docs.docker.com/config/containers/logging/local/#options, this defaults to a 20M file for each log and 5 maximum files (each compressed). 
In a 3 month period, we [expect 15MB for service and 640MB for nginx](https://github.com/getodk/central/issues/231#issuecomment-910864302) for a very active server, so the defaults for 100MB for service (because it's less stuff in docker-compose) and 600MB for nginx seem like good conservative defaults. We can dial the latter down if necessary. …

Enable local driver for log rotation

---

files/nginx/odk.conf.template

Per @issa-tseng's guidance, I tried to do the most narrow change from our pen test. 
The slightly controversial change is increasing the Strict-Transport-Security age and adding always. The age matches the [Moz guide](https://ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=intermediate&openssl=1.1.1d&guideline=5.60) instead of the [Nginx guide](https://www.nginx.com/blog/http-strict-transport-security-hsts-and-nginx/), but I don't think we've done anything dangerous.
Things I tried to verify.
* https://www.ssllabs.com/ssltest/analyze.html?d=dev.getodk.cloud reports the server has TLS 1.3
* https://gf.dev/x-frame-options-test says we prevent click-jacking.
* Enketo logged in submissions and edits work
* Enketo public access links work
* Collect submissions work

Prevent exploitable TLS v1.0 and cross-frame scripting

---

files/nginx/odk.conf.template

This commit aims to prevent excessive caching of /version.txt and /index.html.
Prior to this commit, I noticed the following behavior:
- Open Frontend in a browser.
- Change the source, then rebuild. This will change /version.txt.
- However, if you click on the Version link in the help dropdown, the old /version.txt is shown in a new tab.
- Only if you refresh the new tab is the new /version.txt shown.
getodk/central-frontend#496 only works if requesting /version.txt returns the current version, reflecting any change.
Adding the `Cache-Control` header for /version.txt seems to resolve this issue. I also added it for /index.html, which should make it unnecessary to ever force-refresh /index.html in a browser.
I think `Cache-Control` is useful for these two files, but I don't think that it …

Add Cache-Control header for /version.txt and /index.html

---

files/nginx/certbot.conf
files/nginx/odk-setup.sh
files/nginx/redirector.conf
nginx.dockerfile

Central certs were not able to renew because some of them had the old conf from https://github.com/staticfloat/docker-nginx-certbot/tree/master/src/nginx_conf.d. Instead we need the conf from https://github.com/JonasAlfredsson/docker-nginx-certbot/tree/master/src/nginx_conf.d.
I tried a million ways in the Dockerfile to copy the *.conf files into /etc/nginx/conf.d, but they'd would never appear in the live container, so I reverted to using odk-setup.sh.
My specific changes are...
* Pin docker-nginx-certbot version to 2.4.1 not 2.4 because we don't want any surprises if they release a patch.
* Put the necessary files from https://github.com/JonasAlfredsson/docker-nginx-certbot/tree/master/src/nginx_conf.d into repo and copy to /usr/share/nginx/. This does mean that each time we update …

Fix LetsEncrypt renewal failures

---

enketo.dockerfile

https://github.com/enketo/enketo-express/blob/master/CHANGELOG.md#304---2021-11-04
* Public access links with media and forms with non-ASCII form IDs now load as expected

Upgrade Enketo

---

enketo.dockerfile

Thanks to https://github.com/enketo/enketo-express/issues/163, Enketo can load its config at run time, so we no longer need to run npm and grunt.
I verified this change works by: 
1. Starting from a fresh install from this PR and confirming that form previews and public access links work.
2. Starting from a fresh Central v1.3.3 install, applying this PR, and confirming that old and new form previews and public access links work.

Enketo can now load config at runtime, so rebuilding is not needed

---

docs/news.html

Austria and France have both ruled that GA is not GDPR compliant. Fathom is.
I've deployed it on getodk.org, forum.getodk.org, docs.getodk.org, and xlsform.getodk.org so far and it's working great. 
No cookies are required so I think cross-site issues. That said, it'd be good if someone could confirm that this won't throw up any cross-site errors in Central.

Switch from GA to Fathom

---

files/service/scripts/start-odk.sh

Using a new helper function from central-backend (https://github.com/getodk/central-backend/pull/462) check for any pending migrations and exit the startup script if there are any.
The existence of pending migrations (after they should have run automatically) indicates there was likely an error with the migrations, and the cron jobs and server should not run with the database in an erroneous state. 
Fixes #258

Bug #258: Don't run server if database migrations fail

---

.circleci/config.yml

From CircleCI...
> We are deprecating Ubuntu 16.04-based machine images on CircleCI in preparation for an EOL on Tuesday, May 31, 2022 to ensure your builds remain secure. For a detailed overview of how this will affect your workflow, [read the blog article here](https://circleci.com/blog/ubuntu-14-16-image-deprecation).
> 
> We will also be conducting temporary brownouts on Tuesday, March 29, 2022, and again on Tuesday, April 26, 2022 during which these images will be unavailable.
> 
> We are contacting you because one or more of your projects has a job that uses an Ubuntu 16.04-based image.
> 
> The project(s) using an image based on Ubuntu 16.04 are:
> [central]
> 
> If you have specified an Ubuntu 16.04-based image please see our [migration …

Upgrade to CI to Ubuntu 20 LTS because Ubuntu 16 is EOL

---

files/nginx/common-headers.nginx.conf

Worth considering while reviewing privacy- & security-related headers.  Ref https://developer.mozilla.org/en-US/docs/Web/Security/Referer_header:_privacy_and_security_concerns
E.g. this will marginally decrease the option of opportunistic credential stealing via basic auth dialog.
> When an external resource(e.g. http://foo.com/image.jpeg) is used as the source of an image tag, if the external resource returns a 401 response code and sets a WWW-Authenticate header then the browsers standard 'Basic authentication' dialogue will pop up.. on the [ODK] page.
> While this is standard (and expected) browser behavior it could confuse users and be used in phishing attacks.
> -- _https://jira.atlassian.com/browse/CONFSERVER-28932_

Referrer policy header

---

files/service/pm2.config.js

Closes https://github.com/getodk/central/issues/265?
This change seems to remove the duplicates from `central-backend` logging when run from `docker-compose`.
I haven't had a chance to test this on a real deployment, but _it works on my machine_ :tm: :grin:

pm2: remove duplicate logging

---

files/service/scripts/start-odk.sh

Depends on https://github.com/getodk/central-backend/pull/513

migrations: run provided scripts instead of JS code

---

files/nginx/odk-setup.sh

openssl can fail, leaving an empty file and causing a reboot loop since `/etc/dh/nginx.pem` cannot be found.
During an upgrade to Central v1.5.3, this is what the user saw when the server did not come up.
Logs showed it was an issue with `/etc/dh/nginx.pem`.
Not sure what happened, but it seems that for whatever reason, the openssl command failed and resulted in an empty file.
This PR checks for an empty file in all places where openssl is called. I confirmed the syntax is correct with shellcheck. I also wrap the mkdir command in case we ever use a white space in the name.
I confirmed this fix works on the server that had this issue.

openssl can fail, leaving an empty file and causing a reboot loop

---

service.dockerfile

> This command is similar to npm install, except it's meant to be used
> in automated environments such as test platforms, continuous
> integration, and deployment -- or any situation where you want to
> make sure you're doing a clean install of your dependencies.
>
> - https://docs.npmjs.com/cli/v8/commands/npm-ci/

service: use npm ci

---

files/enketo/generate-secrets.sh
files/enketo/start-enketo.sh
files/nginx/odk-setup.sh
files/service/scripts/start-odk.sh

Closes https://github.com/getodk/central/issues/330
Different shebangs are used because these scripts are currently run in different contexts, specifically:
* `files/enketo/start-enketo.sh`: triggered in `enketo.dockerfile` using [Docker's `CMD`](https://docs.docker.com/engine/reference/builder/#cmd) in _shell_ form; "If you use the shell form of the `CMD`, then the `<command>` will execute in `/bin/sh -c`"
* `files/nginx/odk-setup.sh`: triggered in `nginx.dockerfile`, explicitly using `/bin/bash` there
* `files/service/scripts/start-odk.sh`: triggered via `exec` in `./wait-for-it.sh`, so inherits the shebang from `./wait-for-it.sh`
* `files/enketo/generate-secrets.sh`: triggered by [`docker-compose.yaml`'s `command`](https://docs.docker.com/compose/compose-file/#command), which …

Add shebangs to all shell scripts

---

files/service/scripts/wait-for-it.sh

The `wait-for-it.sh` script was introduced in fcad46fcd38fb67ecb0cb2631fb66b2904f582ed.
It looks like the version at https://github.com/vishnubob/wait-for-it/blob/8ed92e8cab83cfed76ff012ed4a36cef74b28096/wait-for-it.sh, whose licence is MIT and includes the clause:
> The above copyright notice and this permission notice shall be included in all
> copies or substantial portions of the Software.
See: https://github.com/vishnubob/wait-for-it/blob/8ed92e8cab83cfed76ff012ed4a36cef74b28096/LICENSE.

Wait for it licence

---

service.dockerfile

See https://forum.getodk.org/t/service-image-build-fails-due-to-missing-stretch-pgdg-repository/39528
I don't think the correct approach is to hard-code the repo. We should choose the correct repo based on the OS on image because that OS can change. The alternative is to choose an OS-specific build of node, but that also has problems because we have to know when that OS reaches EOL. 
https://www.postgresql.org/download/linux/debian/ has a similar approach to installing psql. Since we don't have lsb_release (and after installing it in the container I couldn't find the binary), I figured I can grep for the codename instead.
The regex I used was pulled from https://unix.stackexchange.com/questions/13466/can-grep-output-only-specified-groupings-that-match. I tested it both in Debian and …

Select the PostgreSQL apt repo based on the OS codename

---

docs/news.html

I've linked to the non-existent 5th post in the v1.5.x thread on the forum. Matt will add that post when he releases. Proposed text:
```
ODK Central v1.5.4 is now available. It includes the following change:
* Select the PostgreSQL apt repo based on the OS codename
This change is necessary to build any version of Central. If you need to build an older version of Central, you can manually make the change as described [in this post](https://forum.getodk.org/t/central-service-image-build-fails-due-to-missing-stretch-pgdg-repository/39528/7).
If you are upgrading from a version older than v1.5.3, please read through [the v1.5.3 notes above](https://forum.getodk.org/t/odk-central-v1-5/37882/4).
```
The build fails because of the fix it announces.

Update news for 1.5.4

---

files/service/scripts/purge-forms.sh
files/service/scripts/reap-sessions.sh
files/service/scripts/run-analytics.sh
files/service/scripts/run-backup.sh

These changes resolve the shellcheck violation:
cd /usr/odk
^---------^ SC2164: Use 'cd ... || exit' or 'cd ... || return' in case cd fails.
An alternative would be to follow `shellcheck`'s suggestion to add `|| exit` to the `cd` invocations, but adding `-e` will also protect against future changes and seems like a reasonable default for scripts:
```
-e errexit       If not interactive, exit immediately if any untested command fails.  The exit
status of a command is considered to be explicitly tested if the command is
used to control an if, elif, while, or until; or if the command is the left
hand operand of an “&&” or “||” operator.
```
`-u` () is a bonus, which also seems like a sensible default for shell scripts in this repo:
```
-u nounset       Write a message to standard error when …
```

scripts: fail if cd fails

---

service.dockerfile

service.dockerfile: don't use apt-key

---

docker-compose.yml

Addresses part of #349
I've upgraded `pyxform` on the staging and dev servers and verified that it works as intended. I believe that without getting this in, it will be reverted on staging if anything else gets merged to `next`.
Given the review and verification we've done, I am fairly confident this is the version we'll release with.

Upgrade pyxform to v1.11.1 with entity creation support

---

files/service/crontab
files/service/scripts/run-backup.sh

Progress toward #323.
I don't think there's a lot to verify here. With this PR, Central will no longer run the lib/bin/backup.js script in central-backend. We will remove that script in a separate Backend PR.
We have to remove run-backup.sh from the crontab. That's the only place that run-backup.sh is used, so we can also remove run-backup.sh.
This change should be low-risk. The main regression risks will come with the changes to central-backend, which will happen in a separate PR.
getodk/docs#1535

Remove Google Drive backups

---

files/prebuild/build-frontend.sh

build-frontend: suppress npm noise

---

docker-compose.yml

Closes #349
Put on dev server, converted a form with `big-image`, verified it works as expected.
This updates to the latest version of https://github.com/getodk/pyxform-http which was updated to the latest version of https://github.com/xlsform/pyxform
Risk of regression is isolated to pyxform entities and media functionality. Both were reviewed and were fairly simple changes so are low-risk.
https://github.com/getodk/docs/issues/1549

Update pyxform to v1.12.0 to support big-image

---

enketo.dockerfile
nginx.dockerfile
service.dockerfile

It seems risky to have multiple statements in a single `RUN` instruction.
In this particular example, it's likely that the final step (`apt-get install`) will fail if one or more earlier steps failed.  But replacing `;` with ` && ` means that:
* build will fail faster if an early step fails
* if this pattern is copied elsewhere, we might avoid obscure bugs

Run linked commands with &&

---

files/prebuild/build-frontend.sh

Depends on #362 - please do not review until that is merged.
> This command is similar to npm install, except it's meant to be used
> in automated environments such as test platforms, continuous
> integration, and deployment -- or any situation where you want to
> make sure you're doing a clean install of your dependencies.
>
> - https://docs.npmjs.com/cli/v8/commands/npm-ci/

frontend: use npm ci

---

docker-compose.yml

https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/VersionManagementConsiderations.html suggest upgrades to 6.0 are very safe. Kobo runs [6.2](https://github.com/kobotoolbox/kobo-docker/blob/HEAD/docker-compose.backend.template.yml#L42) so that’s also likely safe. I wanted to push the boundaries and try the latest.
I tested this works by starting with a v2023.1.0 install...
* Confirm form preview, form submission, and form edit work before upgrade.
* Confirm form preview, form submission, form edit, and web link submission, work on same form after upgrade.
* Confirm form preview, form submission, and form edit work a new form after upgrade.

Upgrade to redis 7

---

service.dockerfile

This PR updates pm2 to the latest version.
I haven't done much to verify this change to the patch version. If there is an issue, then CircleCI or regression testing should help catch it.
No change needed.

Update pm2 to latest version

---

postgres_upgrade.dockerfile

Users are generally going to copy these instructions so the path doesn't really matter. We want to keep it out of the root.

Remove resolved TODO

---

docker-compose.yml
files/service/config.json.template

This PR introduces the maintained, drop-in replacement for namshi/smtp. https://github.com/namshi/docker-smtp/issues/81#issuecomment-916291013
I tested this by starting with a v2023.1.0 install, changing to this container, rebuilding, and sending a password reset email through an AWS SMTP server. I've also tested sending a password reset email through the server itself. 
The reason for `ignoreTLS` is that exim now generates a self-signed cert and advertises itself as a TLS-enabled server. nodemailer, the Central library that sends the emails, doesn't like self-signed certs, so that's why there is a few flag.
Alternatives I rejected:
* add `MAIN_TLS_ENABLE = false` to _docker_additional_macros fails because TLS support is compiled in. …

Change from nashmi/smtp to the more maintained ixdotai/smtp

---

nginx.dockerfile
secrets.dockerfile
service.dockerfile

This should be a safe upgrade. I've looked through the [v16](https://raw.githubusercontent.com/nodejs/node/main/doc/changelogs/CHANGELOG_V16.md) and I didn't see anything concerning.

Upgrade from node 16.17.0 to 16.19.1

---

.circleci/config.yml
files/enketo/start-enketo.sh
files/nginx/setup-odk.sh
files/service/scripts/start-odk.sh

The original code looks like it's doing something clever (e.g. protecting secrets from leaking into the `pm2` process?), but I can't work out what it is...

start-enketo: simplify config generation

---

docker-compose.yml
files/nginx/odk.conf.template
files/nginx/setup-odk.sh
nginx.dockerfile

After some discussion with @lognaturel, we've decided that transient volumes are OK for letsencrypt certs. 
Our previous changes didn't address the issue of accidentally requesting multiple certs when rebuilding, and we've confirmed that multiple builds don't actually request more certs. It's only when you do a docker-compose down or build a totally new machine that this is problem. That is to say, it's a problem for ODK Cloud but not for most people.
We've decided to use `/usr/share/odk/nginx/` as the directory we use so we don't accidentally clobber something in `/usr/share/nginx`/.
This PR was confirmed working by testing current version of Central with LetsEncrypt, then applying this PR, and running ` docker compose build && docker compose up -d`. A new cert was requested, but …

Don't use named volumes for nginx

---

instructions.md

Targeting the `master` branch rather than `next` because this is a no-op change to docs.

Remove instructions.md

---

files/enketo/start-enketo.sh

Mirror the change in https://github.com/enketo/enketo-express/pull/533 and the `pm2-runtime` usage in https://github.com/getodk/central/blob/0502d5397faf42b641a16487dbcdea10de418dea/files/service/scripts/start-odk.sh#L43

Use pm2-runtime with Enketo to ensure quick stop

---

service.dockerfile

Follow on from https://github.com/getodk/central/pull/390

Upgrade node

---

enketo.dockerfile
files/enketo/start-enketo.sh
files/nginx/setup-odk.sh
files/service/scripts/start-odk.sh

Closes #416
Did a `docker compose build` `docker compose up -d` `docker compose stop` after each commit to make sure each was minimal and effective. It's still on there if someone wants to do a sanity check.
The underlying issue is that signals weren't being proxied to the intended processes. More at https://stackoverflow.com/a/32261019/137744. This was addressed by running all the various processes with `exec`.
Additionally, the Enketo dockerfile needed to be updated to use the JSON-array syntax so it wouldn't be called with `/bin/sh -c` which is immune to SIGTERM
This is an ops change. Worst case would be things don't stop or come up. I think if it works on dev it's likely to work anywhere.
I'm not entirely sure about risk beyond things not stopping or coming up. ~I keep seeing things …

Speed up stopping containers

---

docs/news.html

Fathom's custom domains are the reason I picked them but that feature doesn't work anymore. Also, it's gotten very expensive for what we use it for.

Replace Fathom with Cloudflare

---

docker-compose.yml
enketo.dockerfile

Closes https://github.com/getodk/central/issues/409
pyxform has a small bug fix.
Enketo has some risk but has been running on https://getodk.org/xlsform and on the QA server for some days.

Update pyxform and Enketo

---

files/postgres14/upgrade/check-available-space

Closes #424
On the dev server, I changed the line changed by this PR to 
```bash
used="$(( $(du -s /var/lib/docker | cut -f1) + 5000000" )) # add 5G of buffer
```
There's about 11G of stuff in that folder and I confirmed that the script said I needed 17G for the update.
I don't have a good strategy for requesting the space check when the migration has already been done (and there's no `postgres` container). I think this is good enough but the reviewer should see whether they agree!
I considered telling the user we were adding a buffer or only adding it in the error message. But this is simple and feels like the most fool-proof.
The issue mentioned the possibility of 10Gb of buffer. That seemed extreme to me.
I'm not totally sure whether the [arithmetic …

Add 5G buffer to space required for postgres upgrade

---

files/postgres/upgrade-postgres.sh

Closes #430
I've tried this on a failing machine and it worked. IMO, it's only slightly less safe than the old version. We ask people in the docs to do a spot check to make sure their data is there. We also do a quick check here in the code.

Remove unreliable check for successful migration

---

files/nginx/odk.conf.template

fixes #438: if URI is given in proxy_pass then nginx decodes and re-encodes path
which breaks submission attachment with special characters in webform more details: https://trac.nginx.org/nginx/ticket/2506
Manually verified it locally and on Dev server
This is simplest and safest fix. I am going to create separate issue to investigate encoding protocol between Central and Enketo.
None
None

fixes #438

---

.github/ISSUE_TEMPLATE.md

This PR adds an issue template that @srujner and @dbemke can use when filing issues. I modified the [Collect issue template](https://github.com/getodk/collect/blob/2d544e1a78174f0427b6f81bc35b6c7baac2c99d/.github/ISSUE_TEMPLATE.md). Suggestions welcome!

Add template for bug reports by QA team

---

docker-compose.yml

Closes #454 
I ran `docker compose config | grep EMAIL_FROM` to see what the config was. 
* with EMAIL_FROM in .env set to odk@foo.org, I get odk@foo.org in the output. 
* with EMAIL_FROM in .env commented out, I get no-reply@odk-central.foo.org in the output.
I also confirmed that emails are delivered with this change.
There might be a bug in docker/compose v2.20.2/24.0.5, but thankfully https://docs.docker.com/compose/environment-variables/env-file/#parameter-expansion says unbraced vars are supported, so that's why this change works.
It should only affect people who might have changed docker-compose.yml. If something's broken when they upgrade, it will be pretty easy to see because they can't create or reset web users. Hopefully that will lead to a forum post or this issuel.

Fix email sending templating bug

---

enketo.dockerfile

Closes #441 
We merged a couple of risky prs to pyxform so I think we should hold off a little longer on releasing and upgrading as we catch things from https://getodk.org/xlsform/
We don't have another Enketo release planned. 6.2.2 has been on the dev server and https://getodk.org/xlsform/ for about a week now.

Update Enketo version to 6.2.2

---

files/postgres14/upgrade/check-available-space

Closes #439
Sometimes people run the disk space checker after a failed upgrade or maybe they are using compose v2 with an pre-migration install. See https://forum.getodk.org/t/stuck-on-central-upgrade/41421/3
This is an issue because v1 used `_` in names and v2 uses `-`.
Ran the script on a machine with compose v2. I did NOT run it on a machine with v1.
The change isn't very robust because you could have used compose v1 to setup Central and still have v2 in your path, but I can't think of a way to check what version of compose was used to setup the current install.
You can force docker to [use the v1 scheme](https://stackoverflow.com/questions/69464001/docker-compose-container-name-use-dash-instead-of-underscore), but that doesn't really help with this script.
Anyway, seems like this …

Adjust container name if you have compose v2

---

.gitignore
docker-compose.yml
files/dkim/config.disabled

DKIM is essentially a requirement to get emails delivered, so my high-level goal is to make it easier to turn on, without having to risk merge conflicts. Some things that you should know about the SMTP container.
* It needs to have an existing file or the volume mapping will create an empty folder. That's why `rsa.empty` is there as a place holder in the compose file. It prevent that from happening.
* It expects the `rsa.private` file at `/etc/exim4/dkim.key.temp` so that's why that's hard coded in the compose file.
* It enables DKIM when `DKIM_KEY_PATH` has a value, so by default, we set it to empty, via `DKIM_CONTAINER_KEY` to disable it. Only when `DKIM_CONTAINER_KEY` has a value will DKIM be enabled. And the container expects this value to be the same as the container location of the …

Improve DKIM support

---

files/postgres14/start-postgres.sh
postgres14.dockerfile

Closes #419
```bash
docker compose build postgres14
docker compose up -d postgres14
docker compose stop
```
This is using all the same strategies as described in https://github.com/getodk/central/pull/417 I delayed this one because I didn't have a local setup at the time.
As far as I know, there's no risk.
No.

Speed up stopping postgres14 container

---

docker-compose.yml

Both of our base images ultimately inherit from the official docker-postgres image.  This has an env var POSTGRES_DB, and has never referenced POSTGRES_DATABASE.
See: https://hub.docker.com/_/postgres/
See: https://github.com/docker-library/postgres

Rename POSTGRES_DB env var

---

nginx.dockerfile
secrets.dockerfile
service.dockerfile

- Built using `node:18-slim` instead of `node:18.17`.
- I assumed we probably want patch versions of node that shouldn't be breaking.
- Is the assumption correct, or should I change back to pinned `18.17`?
- Merged RUN directives where possible
- This was less significant than I thought, maybe 50 - 100 MB saving.
- The dockerfile was missing a cleanup of the apt list here too: https://github.com/getodk/central/blob/774b491961578bd6e03ceaa6cf8032dd27b828a7/service.dockerfile#L21-L22
- Absolute paths for WORKDIR (as per dockerfile-utils linting).
- Add HEALTHCHECK. This is useful for docker-compose setups. It's ignored in Kubernetes.
- Remove deprecated EXPOSE command and replace with LABELs.
I image the reason for not using a slim image originally is because they don't have git installed …

Use slim node images to reduce download and running size

---

docker-compose.yml
nginx.dockerfile

Closes https://github.com/getodk/central/issues/497
- Ran the updated smtp image on Digital Ocean and verified email sending attempts work the same way
- Reviewed the nginx-certbot diff and verified that there are no changes to `redirector.conf`. Put upgrade on dev server
Changes are fairly minimal for the nginx-certbot image, there just is one technically breaking change.
Uses latest versions.
Neither upgrade looks very risky.
No.

Dependency updates

---

files/service/scripts/start-odk.sh

Closes #577
- Correctly export the `WORKER_COUNT` variable in `start-odk.sh`, otherwise the value is not respected (see screenshots).
- This is because `pm2.config.js` uses `process.env.WORKER_COUNT`, but the variable is only available in the bash shell, not the pm2 command (it needs to be exported for that).
- Fixed the determination of the available memory:
- Currently the `vmstat` command gets the total available memory on the **host system**.
- To get the available memory from either the host machine OR a restricted container in docker compose / Kubernetes, we need to inspect the cgroup.
- Added an optional for environment variable `WORKER_COUNT` for the backend service.
- If this value is provided, it overrides the automatically generated value for `WORKER_COUNT`.
- Added the empty …

Determining backend memory limit from container cgroup

---

docker-compose.yml
docs/news.html
enketo.dockerfile

I have a draft forum post ready to go at https://forum.getodk.org/t/odk-central-v2023-5-entity-updates-via-submissions/44311/2
This branch is currently running on https://dev.getodk.cloud I verified converting a form with pyxform and making submissions with Enketo.
We've now fixed all known issues coming out of the pyxform 2.0.0 changes so it feels like a good time to upgrade pyxform.
Enketo as currently in Central v2023.5.0 changes annotation files any time an edit is made to the corresponding submission, whether or not the edit involved changes to the annotation file. That seems worth fixing asap.
I believe the pyxform change is very low risk. The Enketo change will be somewhat disruptive because it rolls back some improvements but I think it's the right call (see …

Prep v2023.5.1

---

docker-compose.yml

Recent versions of Docker will show a warning if there is a version key. Removing the key fixes the problem.

Leaving version in docker-compose results in warning

---

files/postgres14/upgrade/check-available-space

As shown at https://forum.getodk.org/t/how-to-upgrade-central-from-v1-5-3-to-latest/45797/10
The check disk command doesn't work because even if you have compose v2 installed, if the container was launched with v1, it will have underscores in the name. This patch checks to see if there is a running container with underscores and returns a 1 or 0.
I haven't tested this on a real system, but I have verified the individual docker and grep commands work as expected.

Check if running container was launched with compose v1

---

files/nginx/client-config.json.template
files/nginx/odk.conf.template
files/prebuild/build-frontend.sh
files/prebuild/write-client-config.sh
nginx.dockerfile

This PR makes progress on getodk/central#656. It generates the Frontend config and serves it so that Frontend can then fetch it. The corresponding Frontend PR is getodk/central-frontend#988.
So far just that CI passes. Once it's on staging, I can double-check that /client-config.json is served correctly.
I'm going to leave comments about a few lines.
getodk/central-frontend#988 mentions the cost of an additional request. I don't think it will be much of an issue.

Generate Frontend config and serve it

---

.circleci/config.yml

When I view a build in CircleCI, I see the following warning (e.g., [here](https://app.circleci.com/pipelines/github/getodk/central/927/workflows/cdc558cb-6857-419e-9fc2-b555b2069a07/jobs/972)):
> This job is using a [deprecated](https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/) image 'ubuntu-2004:202201-02', please update to a newer image
This PR resolves the warning by updating the image.
CircleCI continues to pass.
This PR targets the current version of Ubuntu 20.04. If we were concerned that we might introduce something to Central that would work in a new version of Ubuntu 20.04, but not an older one, we could intentionally target an older version. It looks like one of the [options](https://circleci.com/docs/linux-vm-support-policy/) is `previous`, which is …

Update image used for CircleCI

---

.github/workflows/ghcr.yml
docker-compose.yml
files/nginx/setup-odk.sh
nginx.dockerfile

Closes #165
Progress towards https://github.com/getodk/central/issues/656
Based on #249, https://github.com/getodk/central/pull/546
TODO:
The built images can be seen at https://github.com/lognaturel/central/pkgs/container/central-nginx and https://github.com/lognaturel/central/pkgs/container/central-service
I have verified that the service image + nginx image with custom certs work with the standard Docker Compose file.
I mostly followed the groundwork laid by @mattelacchiato in #249 and then @tobiasmcnulty at #546 with some further simplifications.
I used the image naming suggested by @tobiasmcnulty: `central-service` and `central-nginx`. I considered calling them frontend and backend but I think matching the Dockerfile names is the least confusing option.
It doesn't affect users yet …

Add workflow to publish nginx and service images to GHCR

---

files/service/crontab
files/service/scripts/process-backlog.sh

Related to backend PR https://github.com/getodk/central-backend/pull/1172
I decided to run this at 2am. We used to do backups then, but that seems to have been removed from the crontab. This shouldn't interfere with running the purge command later because force processing things in the backlog will safely work around soft-deleted forms/submissions the same as purged submissions.

Crontab job for force processing submission backlog of offline entities

---

nginx.dockerfile
service.dockerfile

Resolves warnings:
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match

Dockerfiles: make keyword case consistent

---

.github/workflows/test-nginx.yml
docker-compose.yml
enketo.dockerfile
nginx.dockerfile
secrets.dockerfile
service.dockerfile
test/nginx-test.dockerfile

Closes #649
Tried on dev, verified basic happy paths.
I searched for the previous node version so hopefully got all of those this time!
There are no significant expected changes in behavior. pyxform and Enketo releases are relatively small. No major version bumps anywhere.
No.

Update v2024.2.0 deps

---

files/prebuild/write-client-config.sh

I don't see anything running write-client-config.sh, so I think it's safe to remove that file. It looks like #676 added the code in write-client-config.sh to another file, so doesn't run the script anymore.

Remove write-client-config.sh

---

.github/workflows/test-nginx.yml

Don't fail log output build steps if the corresponding docker image never started, e.g.
Error response from daemon: No such container: test-enketo-1
This makes the github actions GUI less confusing and quicker to navigate to the real build failure.

ci: don't fail log-output steps

---

test/mock-http-server/index.js
test/test-nginx.js

This header's value is relied on in both central-backend and enketo.

test-nginx: assert x-forwarded-proto header is always https

---

docker-compose.yml

Closes #
Made docker-compose change on dev, verified I can convert a form with geojson attachment.
This fix comes in Validate where we've added the jackson dependency back in. Ideally we would not need it but for now this fix brings back broken functionality.
Should just fix geojson support. That's all that's changed across the stack.
No.

Update pyxform to fix geojson support

---

test/test-nginx.js

* /.well-known/acme-challenge path isn't relevant to these tests, as they do not use letsencrypt SSL certs
* in the test scenario, specific handling for /.well-known/acme-challenge is removed from redirector.conf in files/nginx/setup-odk.sh
* the tests don't make sense, as they're checking for 404s

test/nginx: remove letsencrypt-specific tests

---

service.dockerfile

Removed from backend codebase in https://github.com/getodk/central-backend/pull/1293

service: remove --legacy-peer-deps from backend init

---

files/prebuild/build-frontend.sh
nginx.dockerfile
test/nginx.test.docker-compose.yml

This significantly decreases test turnaround time.
```sh
./run-tests; time ./run-tests.sh
```
* with this PR: 14 seconds
* without this: 90 seconds
It looks like CI time is also decreased from ~1m45 to ~1m
* complicates build script (`build-frontend.sh`)
CI.
Other options might be to:
* override the `client` directory in test envs
* use a different dockerfile in tests
* override `build-frontend.sh` in test envs
No effect.
No.

nginx: skip frontend build in tests

---

files/nginx/odk.conf.template
files/nginx/setup-odk.sh

Working on #809 I noticed that the location of SSL certs is based either on the domain name, or on the method of supply of SSL certs.
Cert provision approach should probably not affect the nginx "server_name" setting.
Also, the old variable name `CNAME` (short for "certificate name?") is easily confused with the DNS concept of CNAME records ("canonical names") (https://en.wikipedia.org/wiki/CNAME_record).
Ran tests.
It may not be - there may be a subtle reason for the current use and/or naming of `CNAME`.
Behaviour that may have accidentally been affected:
Servers with `SSL_TYPE` = `"customssl"` may have their nginx `server_name` changed.  This is probably a positive change - currently it has no effect, but will do once #809 is merged.
It should not.

nginx: separate cert paths from server_name

---

.github/workflows/test-nginx.yml
docker-compose.yml
enketo.dockerfile
nginx.dockerfile
secrets.dockerfile
service.dockerfile
test/mock-http-server/package-lock.json

Closes #732
Tried pyxform-http, enketo on dev server

Upgrade dependencies for v2024.3.

---

test/test-nginx.js

This comment was merged as part of #809, but was not correct by the time the PR was merged.

test/nginx: remove misleading comment

---

docs/outdated-version.html
docs/style.css

add outdated-version.html

---

docs/outdated-version.html

This PR updates the translations in outdated-version.html based on the latest translations. The new translations were automatically pulled from Transifex and can be seen in getodk/central-frontend#1108. This PR makes progress on #731.
Note that I am intentionally targeting the `master` branch.
Only translations should have changed in this PR.

Update translations in docs/ before release of v2024.3

---

files/service/scripts/start-odk.sh

Closes #875 
- The original check for cgroups v1.
- A check for cgroups v2.
- If there are memory constraints set, then they are used.
- If there are no memory constraints, the value will be set to `max` and we fallback to use the total memory available on the system.
- Note that it's possible to determine hard and soft memory limits via cgroups, but this is probably overkill.
- Tested on my local Debian Bookworm setup (using WSL, so it's cgroups v1).
- Tested on a Debian Bookworm remote server, using cgroups v2.
- It seems to be a pretty common way to determine memory available inside a container.
- Containers are essentially wrappers for standard tools such as cgroups, so the total memory available in the container is determined by a cgroup.
- It doesn't require any additional tools / …

Update start-odk.sh memory calculation to support cgroups v2

---

README.md

Follow-up from v2024.3 retrospective. In that release, we upgraded node to 22 and I had some hesitation around when it should be done and by whom.
I considered explicitly saying that I do the upgrade similar to what [Collect does](https://github.com/getodk/collect/?tab=readme-ov-file#release-cycle) but I don't think it's necessary until we decide to document more of the release process here.
While here I changed the heading syntax to use `#` because it allows deeper nesting and I think it's easier to read.
Targets `master` since it's docs only.
Read it.
It provides the info succinctly.
No user-facing change, this just documents existing process.
This is the docs update.

Add Node version update process

---

files/service/scripts/start-odk.sh

Currently, if check-migrations fails with non-1 exit code, the server will continue to start.
The existing check-migrations call and test for exit code 1 was originally introduced as a fix for #461.  The change in this PR should be more robust than the existing approach, but `set -e` and `set -o pipefail` might provide even more safety in handling failures in this script.  These latter options would also allow for complete removal of `make check-migrations` from production.
There may also be other critical scripts in this repo which would benefit from similar changes.
Run tests, shellcheck.
As above, there are more complicated solutions which can improve and simplify this script.  However, they are also more invasive.  This change seems to be simple and an incremental improvement, so can …

service/start: check check-migrations failure more robustly

---

docker-compose.dev.yml

Allowing access to enketo's redis instances locally allows this docker-compose environment to be used to work on enketo-express as well as other central services:
1. run in this repo:
make stop && make dev && docker compose stop enketo
2. run in `enketo` repo:
yarn workspace enketo-express grunt develop
Tested locally.
No other approaches considered.
No effect.
No.

dev: docker-compose: expose redis locally

---

.github/workflows/test.yml

Noted while working on #830.
-----
In commit b2a9d4f933c92324013eaf85bca834c6c0919c56, the directory name containing the nginx tests was changed from `test` to `nginx`.  `docker compose` uses the parent directory name as the default name for containers, so this change broke log output which refers to specific docker logs by container name.
Checked in CI: https://github.com/getodk/central/actions/runs/13430512089/job/37521224773
In commit b2a9d4f933c92324013eaf85bca834c6c0919c56, the directory name containing the nginx tests was changed from test to nginx. docker compose uses the parent directory name as the default name for containers, so this change broke log output which refers to specific docker logs by container name.
The approach in this commit should be more robust as:
1. it uses …

ci/nginx: fix log output

---

files/enketo/generate-secrets.sh
files/prebuild/write-version.sh
files/service/scripts/process-backlog.sh
files/service/scripts/purge.sh
files/service/scripts/reap-sessions.sh
files/service/scripts/run-analytics.sh
files/service/scripts/start-odk.sh
test/check-scripts.sh
test/nginx/run-tests.sh

Incidental to #891.
Whitespace changes can be introduced inadvertently due to different editor configurations.  These changes then add noise to PRs, and if committed, add noise to future diffs and the git log.
This PR adds checks for the following in `.sh` files:
* trailing spaces on lines
* trailing newlines in files
* tabs vs spaces
Added new tests!
The status quo could be maintained.
No effect.
No.

test/check-scripts: add checks to standardise whitespace

---

files/service/scripts/start-odk.sh
test/test-images.sh

In some circumstances, `npx` will transparently install packages when asked to run a command.
From https://docs.npmjs.com/cli/v8/commands/npx#description:
> If any requested packages are not present in the local project dependencies, then they are installed to a folder in the npm cache, which is added to the PATH environment variable in the executed process. A prompt is printed (which can be suppressed by providing either `--yes` or `--no`).
Ref https://github.com/vuejs/vue-cli/commit/f36a4edfbd2bca485e64761d75490e06948abdc9
Existing test suite.
It's safer for it to fail when dependencies are missing.
If `npx` dependencies are not available, this should be caught by this repo's test suite.
No.

Block automatic npx package installation

---

files/nginx/odk.conf.template

Closes getodk/central#906
Manual verification
This is necessary to make webhistory routing mode work correctly in the frontend (Vue). Change is suggested at https://router.vuejs.org/guide/essentials/history-mode.html#nginx
None
No

Features C#906: Enable web history for vue route, catch-all to index.html

---

.github/workflows/test.yml
docker-compose.yml
nginx.dockerfile
secrets.dockerfile
service.dockerfile
test/nginx/mock-http-server/index.js
test/nginx/mock-http-server/package-lock.json
test/nginx/mock-http-server/package.json
test/nginx/package-lock.json

Closes #862
- `service`
- `nginx`
- `secrets`
Leaving smtp image alone. The latest release doesn't have meaningful changes since the one we have and it's deprecated in favor of a fork. I'll handle that switch over in the next release.
Ran tests.
I considered not upgrading Express to 5 but it's for a test so there's no real risk.
The only risky part I can think of is the redis upgrade because we use it as mostly a black box for Enketo. Still, it's a minor version (major coming soon), and I think we'll be able to tell quickly on staging if there are problems.
No.

Update infrastructure dependencies for v2025.1.0

---

files/nginx/odk.conf.template
nginx.dockerfile
test/nginx/mock-http-server/index.js
test/nginx/test-nginx.js

Closes #949
Added new tests.
Existing enketo cache headers are not always present, and sometimes means that immutable resources are not cached.
Should:
* improve caching of immutable resources, giving users faster page-load times
* decrease caching of mutable items, fixing weird behaviours
I don't think so.

enketo: apply HTTP cache strategy

---

.github/workflows/test.yml
files/enketo/generate-secrets.sh
test/test-secrets.sh

@sadiqkhoja these tests demonstrate the issue you observed, and the code changes resolve the `PIPE` error that is thrown (on some systems).
It looks like SIGPIPE is generated when `head` completes more quickly than `tr`.
I think it's more concerning that enketo is happy to start when secrets are missing/empty.
Add tests.
An alternative would be to ignore SIGPIPE (13 / exit code 141).  This seems risky, as there may be other reasons for pipes to fail.
N/A?
No.

ci: test secrets generation

---

files/nginx/odk.conf.template
test/nginx/test-nginx.js

Noted while working on #984 that:
1. these headers were not tested, and
2. cache header changes affected the application of content-security-policy headers
This adds a default more restrictive CSP for routes which do not have other headers set.
New tests for all expected security headers for 200 responses in `test-nginx.js`.
It might also be an option to omit CSP from e.g. API requests.  However, there are various obscure scenarios where a policy can still be helpful, so including a short, very restrictive policy by default seems fail-safe.
This change should not cause regressions, as although the CSP has changed in some cases, it is still set to report-only.
No.

nginx: add missing CSP headers

---

test/nginx/mock-http-server/index.js

The `withStdLogging()` function was behaving as express middleware, while introducing a less idiomatic syntax.  This commit reverts access logs to operate as normal express middleware.
Noted while working on #984
Could have left as-is, but the current syntax hinders adding new tests consistently.
No effect.
No.

test-nginx: use proper express middleware

---

files/nginx/odk.conf.template
test/nginx/test-nginx.js

Corresponding change of https://github.com/getodk/central-frontend/pull/1201

Fixes offline enketo

---

.github/workflows/test.yml

Normal time for this job to complete is 3-4 minutes.  Setting an overall timeout of 10 minutes should allow for occasional slowdown of execution, while preventing runaway build processes from going on forever.
Related: https://github.com/getodk/central/pull/1016
CI.
Simple, and consistent with other CI jobs.
No effect.
No.

ci/test-images: add timeout

---

files/nginx/odk.conf.template
test/nginx/test-nginx.js

Reverts getodk/central#992
After `rewrite ^/enketo-passthrough(/.*)?$ /-$1 ....`, we don't want enketo redirection rules (`/-/...`  -> `/f/...` ) to execute again

Revert "nginx: simplify enketo passthrough rewrites"

---

files/nginx/odk.conf.template
test/nginx/mock-http-server/index.js

Without this PR: nginx returns multiple Vary and Cache-Control headers:
```
curl -I https://staging.getodk.cloud/-/x/css/theme-kobo.css
```

nginx/enketo: strip upstream cache headers

---

files/nginx/odk.conf.template
test/nginx/test-nginx.js

Enketo sends frequent `/-/connection` request to check connectivity, currently nginx is returning 301 therefore Enketo can't send queued submissions even when connection is back.
I have test this change in staging env and verified the functionality in Chrome and Firefox.

do not forward /connection to central-frontend

---

files/nginx/odk.conf.template
test/nginx/test-nginx.js

Closes https://github.com/getodk/central/issues/1048
Put it on the dev server. Verified that there's exactly one `Cache-Control` header and that it's set as expected.
We could also set the headers here to `private, no-cache`, etc. But then we'd be setting duplicate headers which could drift between nginx and backend. I think it's clearer to make caching headers clearly the backend's responsibility.
Note that this does not set the `Pragma` header for backend. I think we could do away with it altogether because it has been deprecated for a long time.
Backend responses should be cached in private caches. We should get 304s.
No.

Pass through backend cache headers

---

files/prebuild/write-version.sh

Closes #1085 
On upgraded server, I get the correct version
```
versions:
4ac522b9ad99ae30ce009a2cbb4c42f1535c561f (v2025.1.1)
550c13d1935a6d33288e6cc00ee9068060bbf810 client (v2025.1.1)
4ea612178d7eb9ef191e8548ef5e70c2084fa8fc server (v2025.1.0)
```
On staging, I get the correct version
```
versions:
721d2d4271724702263e44e0331fa2c6c99b979f (v2025.1.1-1-g721d2d4)
550c13d1935a6d33288e6cc00ee9068060bbf810 client (v2025.1.1)
4ea612178d7eb9ef191e8548ef5e70c2084fa8fc server (v2025.1.0)
```

Get version from each submodule

---

files/nginx/odk.conf.template

gzip_comp_level of 4-6 seems to be the sweet spot for compression and CPU usage. We don't often see huge CPU usage on servers so 5 seems pretty safe. 
gzip_proxied makes sure to gzip anything coming from upstream (reverse proxy mode)
gzip_min_length 1024 is a common default. 1280 suggests we've profiled the responses and we are making a sensible choice, but we haven't. Might as well use the common default.
I've added geojson and svg because we'll be serving those in the future.

Increase gzip level and types

---

files/nginx/odk.conf.template

We set to 5 out of an abundance of caution, but 6 is a much more common default. Unless there is a really good reason, we should just do what everyone else is doing as far as settings.

Use the gzip compression level most CDNs use
